# Sample ResourceBundle properties file

#JNDI_NAME=java:com/env/Oracle/jndi
#db.login= 	
#db.password= 
driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/uas
duser=root
dpass=Password@123
logfile=logs/uas_log.txt
#dbname=access
